### ISSUE TITLE
New collection: STFIL 

### ISSUE THREAD

**Issue by xmcai2016** [data-preservation-programs/RepPoly#26]
Just got a new member (stfil) in the WG. We want to also sync their payloads from mongo to Polybase.
In the process, change their `miner` to `provider`

**Comment by stephen-pl** [comment]
Here is the pr 
https://github.com/data-preservation-programs/RepPoly/pull/28

**Comment by stephen-pl** [comment]
[https://github.com/data-preservation-programs/RepPoly/pull/28](url)
