### ISSUE TITLE
lassie_bedrock schema bug on polybase 

### ISSUE THREAD

**Issue by xmcai2016** [data-preservation-programs/RepPoly#41]
interface lassie_bedrock {
  id: string;
  bandwidth_bytes_sec: number;
  date_stamp: string;
  end_time: string;
  instance_id: string;
  ~~provider~~  storage_provider_peer_id: string;
  retrieval_id: string;
  start_time: string;
 ~~storage_provider_id~~  provider: string;
  success: boolean;
  time_to_first_byte_ms: number;
}

We don't have to alter past data, just fix this going forward :)

**Comment by stephen-pl** [comment]
Looking at mainnet the provider field should be correct. I am going to close the issue. 

![Image](https://github.com/data-preservation-programs/RepPoly/assets/139834872/acbd5268-4994-469d-ab99-33e7dfd6aebd)
